version: '3.3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'PoolerDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'pooler_user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'pooler_password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    volumes:
      - ./db_files:/var/lib/mysql
# Names our volume
volumes:
  db_files:
