CREATE TABLE IF NOT EXISTS T_SERVICES (
    C_ID       INT NOT NULL AUTO_INCREMENT,
    C_NAME     VARCHAR(255) NOT NULL,
    C_URL    VARCHAR(255) NOT NULL,
    C_STATUS    VARCHAR(128) NOT NULL,
    C_CREATED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    C_MODIFIED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    C_UPDATED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (C_ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_STATUS_HISTORY (
  C_ID       INT NOT NULL,
  C_NAME     VARCHAR(255) NOT NULL,
  C_URL    VARCHAR(255) NOT NULL,
  C_STATUS    VARCHAR(128) NOT NULL,
  C_UPDATED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
